<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ApplicationIcon>bulbasaur_icon-icons.com_67580.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.5" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.5" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="bulbasaur_icon-icons.com_67580.ico" />
    <Resource Include="Resources\bulbasaur_icon-icons.com_67580.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TODO.MD" />
  </ItemGroup>

</Project>
